# Generated by Django 3.0.6 on 2024-02-07 16:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=190, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(db_index=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=190, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(db_index=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_regions', to='places.Regions')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=190, null=True)),
                ('prov_code', models.CharField(blank=True, max_length=190, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(db_index=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province', to='places.Provinces')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_regions', to='places.Regions')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
