# Generated by Django 3.0.6 on 2024-02-07 16:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecastattributes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('membership', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('accept_disclaimer', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.TextField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('time_interval', models.CharField(blank=True, max_length=255, null=True)),
                ('csr', models.CharField(blank=True, default='CRS:84', max_length=255, null=True)),
                ('spatialbounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('layer_id', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=400)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('palette', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('color_scale_min', models.IntegerField(blank=True, null=True)),
                ('color_scale_max', models.IntegerField(blank=True, null=True)),
                ('data_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecastattributes.DataSeries')),
                ('forecast_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecastattributes.ForecastModel')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecastattributes.Scenario')),
                ('time_window', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forecastattributes.TimeWindow')),
                ('value_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecastattributes.ValueType')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecastattributes.Variable')),
                ('year_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecastattributes.YearPeriod')),
            ],
        ),
    ]
