# Generated by Django 3.0.6 on 2024-02-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSeries',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('order_item', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order_item'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('order_item', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order_item'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('order_item', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order_item'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeWindow',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('order_item', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order_item'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueType',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('order_item', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order_item'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('order_item', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order_item'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YearPeriod',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('order_item', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order_item'],
                'abstract': False,
            },
        ),
    ]
