"""add description italian and display name to conf param value

Revision ID: 04856adc278f
Revises: aa4ae1a978d9
Create Date: 2024-07-01 10:59:19.496584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '04856adc278f'
down_revision: Union[str, None] = 'aa4ae1a978d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurationparametervalue', sa.Column('display_name_english', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('configurationparametervalue', sa.Column('display_name_italian', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('configurationparametervalue', sa.Column('description_italian', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configurationparametervalue', 'description_italian')
    op.drop_column('configurationparametervalue', 'display_name_italian')
    op.drop_column('configurationparametervalue', 'display_name_english')
    # ### end Alembic commands ###
