"""added display name for coverage configuration

Revision ID: 37c860e5bc45
Revises: a8431c06b228
Create Date: 2024-06-24 17:18:21.128283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '37c860e5bc45'
down_revision: Union[str, None] = 'a8431c06b228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coverageconfiguration', sa.Column('display_name_english', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('coverageconfiguration', sa.Column('display_name_italian', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coverageconfiguration', 'display_name_italian')
    op.drop_column('coverageconfiguration', 'display_name_english')
    # ### end Alembic commands ###
