"""added relationship between coverage conf and observation

Revision ID: 4ee22416b0ee
Revises: 7a6e61611951
Create Date: 2024-05-13 10:34:16.297450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ee22416b0ee'
down_revision: Union[str, None] = '7a6e61611951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MONTHLY', 'SEASONAL', 'YEARLY', name='observationaggregationtype').create(op.get_bind())
    op.add_column('coverageconfiguration', sa.Column('observation_variable_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('coverageconfiguration', sa.Column('observation_variable_aggregation_type', postgresql.ENUM('MONTHLY', 'SEASONAL', 'YEARLY', name='observationaggregationtype', create_type=False), nullable=True))
    op.create_foreign_key(None, 'coverageconfiguration', 'variable', ['observation_variable_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coverageconfiguration', type_='foreignkey')
    op.drop_column('coverageconfiguration', 'observation_variable_aggregation_type')
    op.drop_column('coverageconfiguration', 'observation_variable_id')
    sa.Enum('MONTHLY', 'SEASONAL', 'YEARLY', name='observationaggregationtype').drop(op.get_bind())
    # ### end Alembic commands ###
