"""replaced variable unit with unit_english

Revision ID: 5ae686c67a6e
Revises: fc7c5ef30054
Create Date: 2024-07-02 12:04:29.522490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ae686c67a6e'
down_revision: Union[str, None] = 'fc7c5ef30054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('unit_english', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('variable', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('variable', 'unit_english')
    # ### end Alembic commands ###
