"""add station code

Revision ID: 6e78431f779f
Revises: d99d5d952558
Create Date: 2024-04-10 19:20:40.149103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6e78431f779f'
down_revision: Union[str, None] = 'd99d5d952558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'station', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station', type_='unique')
    op.drop_column('station', 'code')
    # ### end Alembic commands ###
