"""replaced variable description with description_english

Revision ID: 7e4cf01e49bd
Revises: 04856adc278f
Create Date: 2024-07-02 11:59:52.639381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e4cf01e49bd'
down_revision: Union[str, None] = '04856adc278f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('description_english', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('variable', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('variable', 'description_english')
    # ### end Alembic commands ###
