"""rename conf param value description

Revision ID: aa4ae1a978d9
Revises: d802f56efda5
Create Date: 2024-07-01 10:58:16.529050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa4ae1a978d9'
down_revision: Union[str, None] = 'd802f56efda5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurationparametervalue', sa.Column('description_english', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('configurationparametervalue', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurationparametervalue', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('configurationparametervalue', 'description_english')
    # ### end Alembic commands ###
