"""add cascade rules for monthly measurements

Revision ID: bbac959a8e3c
Revises: 659d9a1a2586
Create Date: 2024-04-24 16:30:04.179575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bbac959a8e3c'
down_revision: Union[str, None] = '659d9a1a2586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('monthlymeasurement_variable_id_fkey', 'monthlymeasurement', type_='foreignkey')
    op.drop_constraint('monthlymeasurement_station_id_fkey', 'monthlymeasurement', type_='foreignkey')
    op.create_foreign_key(None, 'monthlymeasurement', 'station', ['station_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'monthlymeasurement', 'variable', ['variable_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monthlymeasurement', type_='foreignkey')
    op.drop_constraint(None, 'monthlymeasurement', type_='foreignkey')
    op.create_foreign_key('monthlymeasurement_station_id_fkey', 'monthlymeasurement', 'station', ['station_id'], ['id'])
    op.create_foreign_key('monthlymeasurement_variable_id_fkey', 'monthlymeasurement', 'variable', ['variable_id'], ['id'])
    # ### end Alembic commands ###
