"""added conf param value sort_order

Revision ID: c6f618a7f88f
Revises: 400c6e807767
Create Date: 2024-10-11 10:54:49.432153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c6f618a7f88f'
down_revision: Union[str, None] = '400c6e807767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurationparametervalue', sa.Column('sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configurationparametervalue', 'sort_order')
    # ### end Alembic commands ###
