"""add description italian and display name to conf param

Revision ID: d802f56efda5
Revises: 0614edfff467
Create Date: 2024-07-01 10:39:40.401206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd802f56efda5'
down_revision: Union[str, None] = '0614edfff467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurationparameter', sa.Column('description_italian', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('configurationparameter', sa.Column('display_name_english', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('configurationparameter', sa.Column('display_name_italian', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configurationparameter', 'display_name_italian')
    op.drop_column('configurationparameter', 'display_name_english')
    op.drop_column('configurationparameter', 'description_italian')
    # ### end Alembic commands ###
