"""add-uncertainty-cov-conf-relationships

Revision ID: e8bc68ec327b
Revises: 9f2dedc5396e
Create Date: 2024-05-17 15:47:58.878242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8bc68ec327b'
down_revision: Union[str, None] = '9f2dedc5396e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coverageconfiguration', sa.Column('uncertainty_lower_bounds_coverage_configuration_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('coverageconfiguration', sa.Column('uncertainty_upper_bounds_coverage_configuration_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'coverageconfiguration', 'coverageconfiguration', ['uncertainty_lower_bounds_coverage_configuration_id'], ['id'])
    op.create_foreign_key(None, 'coverageconfiguration', 'coverageconfiguration', ['uncertainty_upper_bounds_coverage_configuration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coverageconfiguration', type_='foreignkey')
    op.drop_constraint(None, 'coverageconfiguration', type_='foreignkey')
    op.drop_column('coverageconfiguration', 'uncertainty_upper_bounds_coverage_configuration_id')
    op.drop_column('coverageconfiguration', 'uncertainty_lower_bounds_coverage_configuration_id')
    # ### end Alembic commands ###
