"""add description to coverage configuration

Revision ID: f6b6c5d996a6
Revises: 37c860e5bc45
Create Date: 2024-07-01 10:23:55.158130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f6b6c5d996a6'
down_revision: Union[str, None] = '37c860e5bc45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coverageconfiguration', sa.Column('description_english', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('coverageconfiguration', sa.Column('description_italian', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coverageconfiguration', 'description_italian')
    op.drop_column('coverageconfiguration', 'description_english')
    # ### end Alembic commands ###
