"""added variable display_name

Revision ID: fc7c5ef30054
Revises: 7e4cf01e49bd
Create Date: 2024-07-02 12:02:04.620769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc7c5ef30054'
down_revision: Union[str, None] = '7e4cf01e49bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('display_name_english', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('variable', sa.Column('display_name_italian', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('variable', sa.Column('description_italian', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('variable', sa.Column('unit_italian', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variable', 'unit_italian')
    op.drop_column('variable', 'description_italian')
    op.drop_column('variable', 'display_name_italian')
    op.drop_column('variable', 'display_name_english')
    # ### end Alembic commands ###
